# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Do as the shell does.
email: Andreas.Krueger@innoQ.com
description: > # this means to ignore newlines until "baseurl:"
  Workshop material for innoQ event 2016-02-25.
baseurl: "/do-as-shell-does-workshop" # the subpath of your site, e.g. /blog
url: "http://innoq.github.io"
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
